"""
Django settings for pronutrition_project project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv # Importar la librería
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

os.environ['PATH'] = r'C:\Program Files\QGIS 3.34.12\bin;' + os.environ['PATH']
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/


# Cargar variables de entorno desde el archivo .env
load_dotenv(os.path.join(BASE_DIR, '.env'))

# Ahora puedes usar os.getenv() o os.environ.get() para acceder a las variables
SECRET_KEY = os.getenv('SECRET_KEY', 'una_llave_secreta_por_defecto_si_no_esta_en_env') # Es bueno tener un default para SECRET_KEY
DEBUG = os.getenv('DEBUG', 'False').lower() == 'true' # Convertir string a booleano

ALLOWED_HOSTS = [] # Configurar según sea necesario, especialmente para producción




# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.gis',  # App de GeoDjango
    # Tus apps (las crearemos a continuación)
    'core.apps.CoreConfig', # O solo 'core' si no defines una Config específica
    'usuarios.apps.UsuariosConfig', # O solo 'usuarios'
    'ambientacion.apps.AmbientacionConfig', # O solo 'ambientacion'
    # ... y las otras apps a medida que las crees
    'crispy_forms',
    'crispy_bootstrap5',
    'planificacion'
]
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'pronutrition_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'pronutrition_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.contrib.gis.db.backends.postgis',
        'NAME': os.getenv('DATABASE_NAME'),
        'USER': os.getenv('DATABASE_USER'),
        'PASSWORD': os.getenv('DATABASE_PASSWORD'),
        'HOST': os.getenv('DATABASE_HOST'),
        'PORT': os.getenv('DATABASE_PORT'),
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/




# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


LANGUAGE_CODE = 'es-uy' # Español de Uruguay
TIME_ZONE = 'America/Montevideo'
USE_I18N = True
USE_L10N = True # Para formatos de fecha/número localizados
USE_TZ = True


STATIC_URL = '/static/'
# STATIC_ROOT = BASE_DIR / 'staticfiles' # Para producción
# STATICFILES_DIRS = [BASE_DIR / "static"] # Para desarrollo, si tienes una carpeta static a nivel de proyecto

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

LOGIN_REDIRECT_URL = '/' # A dónde ir después del login
LOGOUT_REDIRECT_URL = '/' # A dónde ir después del logout

GDAL_LIBRARY_PATH = r'C:\Program Files\QGIS 3.34.12\bin\gdal309.dll'
GEOS_LIBRARY_PATH = r'C:\Program Files\QGIS 3.34.12\bin\geos_c.dll'
PROJ_LIB = r'C:\Program Files\QGIS 3.34.12\share\proj'


CRISPY_ALLOWED_TEMPLATE_PACKS = ["bootstrap5"]
CRISPY_TEMPLATE_PACK = "bootstrap5"