# Generated by Django 5.2 on 2025-05-07 17:59

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_razon_social', models.CharField(max_length=255, verbose_name='Nombre o Razón Social')),
                ('nombre_fantasia', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre de Fantasía')),
                ('rut', models.CharField(blank=True, max_length=12, null=True, unique=True, verbose_name='RUT')),
                ('direccion', models.CharField(blank=True, max_length=300, null=True, verbose_name='Dirección Fiscal')),
                ('telefono', models.CharField(blank=True, max_length=50, null=True, verbose_name='Teléfono')),
                ('email_contacto', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email de Contacto')),
                ('otros_atributos', models.JSONField(blank=True, help_text='JSON para atributos adicionales no estructurados.', null=True, verbose_name='Otros Atributos')),
                ('fecha_alta', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Alta')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Empresa / Cliente',
                'verbose_name_plural': 'Empresas / Clientes',
                'ordering': ['nombre_razon_social'],
            },
        ),
        migrations.CreateModel(
            name='Establecimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre del Establecimiento')),
                ('ubicacion_descriptiva', models.TextField(blank=True, null=True, verbose_name='Ubicación Descriptiva/Cómo Llegar')),
                ('punto_referencia', django.contrib.gis.db.models.fields.PointField(blank=True, help_text='SRID 32721 para Uruguay.', null=True, srid=32721, verbose_name='Punto de Referencia Geográfico')),
                ('otros_atributos', models.JSONField(blank=True, null=True, verbose_name='Otros Atributos')),
                ('fecha_alta', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Alta')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='establecimientos', to='core.empresa', verbose_name='Empresa Propietaria')),
            ],
            options={
                'verbose_name': 'Establecimiento (Campo)',
                'verbose_name_plural': 'Establecimientos (Campos)',
                'ordering': ['empresa', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_entidad_conceptual', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador único para todas las versiones de este lote.')),
                ('version_numero', models.PositiveIntegerField(default=1, editable=False, verbose_name='Número de Versión')),
                ('fecha_version', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación de Versión')),
                ('estado_version', models.CharField(choices=[('VIGENTE', 'Vigente'), ('HISTORICO', 'Histórico'), ('EN_EDICION', 'En Edición')], default='VIGENTE', max_length=20, verbose_name='Estado de la Versión')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Lote')),
                ('categoria', models.CharField(blank=True, help_text='Ej: i+d, producción', max_length=50, null=True, verbose_name='Categoría del Lote')),
                ('geometria', django.contrib.gis.db.models.fields.MultiPolygonField(help_text='SRID 32721 para Uruguay.', srid=32721, verbose_name='Geometría del Lote')),
                ('superficie_calculada_has', models.FloatField(blank=True, editable=False, help_text='Se calcula automáticamente a partir de la geometría.', null=True, verbose_name='Superficie Calculada (ha)')),
                ('otros_atributos', models.JSONField(blank=True, null=True, verbose_name='Otros Atributos')),
                ('estado_workflow', models.CharField(choices=[('EN_CARGA_GIS', 'En Carga GIS'), ('PENDIENTE_VALIDACION_PRODUCTOR', 'Pendiente Validación Productor'), ('VALIDADO_PRODUCTOR', 'Validado por Productor'), ('CON_AMBIENTACION_EN_PROCESO', 'Con Ambientación en Proceso'), ('ACTIVO', 'Activo'), ('HISTORICO_WF', 'Histórico (Workflow)')], default='EN_CARGA_GIS', max_length=30, verbose_name='Estado en Workflow')),
                ('establecimiento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lotes', to='core.establecimiento', verbose_name='Establecimiento')),
                ('id_version_anterior', models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='version_siguiente_lote', to='core.lote', verbose_name='Versión Anterior')),
            ],
            options={
                'verbose_name': 'Lote',
                'verbose_name_plural': 'Lotes',
                'ordering': ['establecimiento', 'nombre', '-version_numero'],
            },
        ),
        migrations.CreateModel(
            name='Ambiente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_entidad_conceptual', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador único para todas las versiones de este ambiente.')),
                ('version_numero', models.PositiveIntegerField(default=1, editable=False, verbose_name='Número de Versión')),
                ('fecha_version', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación de Versión')),
                ('estado_version', models.CharField(choices=[('VIGENTE', 'Vigente'), ('HISTORICO', 'Histórico'), ('EN_EDICION', 'En Edición')], default='VIGENTE', max_length=20, verbose_name='Estado de la Versión')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Ambiente')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('categoria', models.CharField(blank=True, max_length=100, null=True, verbose_name='Categoría del Ambiente')),
                ('geometria', django.contrib.gis.db.models.fields.MultiPolygonField(help_text='SRID 32721 para Uruguay.', srid=32721, verbose_name='Geometría del Ambiente')),
                ('superficie_has', models.FloatField(blank=True, editable=False, help_text='Se calcula automáticamente a partir de la geometría.', null=True, verbose_name='Superficie (ha)')),
                ('productividad', models.CharField(blank=True, choices=[('A', 'Alta'), ('D', 'D (Por definir significado exacto)'), ('B', 'Baja'), ('OTRA', 'Otra (Especificar)')], max_length=10, null=True, verbose_name='Productividad')),
                ('subindice_productividad', models.CharField(blank=True, max_length=100, null=True, verbose_name='Subíndice Productividad (Texto)')),
                ('relieve', models.CharField(blank=True, max_length=50, null=True, verbose_name='Relieve')),
                ('tipo_suelo_nombre', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tipo de Suelo (Nombre)')),
                ('pendiente_elevada', models.BooleanField(default=False, verbose_name='¿Tiene Pendiente Elevada?')),
                ('erosion_suelo', models.BooleanField(default=False, verbose_name='¿Tiene Erosión de Suelo?')),
                ('otros_atributos', models.JSONField(blank=True, null=True, verbose_name='Otros Atributos')),
                ('estado_workflow', models.CharField(choices=[('EN_CARGA_GIS', 'En Carga GIS'), ('PENDIENTE_VALIDACION_AGRONOMO', 'Pendiente Validación Agrónomo'), ('EN_CORRECCION_GIS', 'En Corrección GIS'), ('ACTIVO', 'Activo'), ('HISTORICO_WF', 'Histórico (Workflow)')], default='EN_CARGA_GIS', max_length=30, verbose_name='Estado en Workflow')),
                ('id_version_anterior', models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='version_siguiente_ambiente', to='core.ambiente', verbose_name='Versión Anterior')),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ambientes', to='core.lote', verbose_name='Lote al que pertenece')),
            ],
            options={
                'verbose_name': 'Ambiente',
                'verbose_name_plural': 'Ambientes',
                'ordering': ['lote', 'nombre', '-version_numero'],
            },
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_tarea', models.CharField(choices=[('DIGITALIZAR_LOTES', 'Digitalizar Lotes'), ('VALIDAR_DIGITALIZACION_LOTES', 'Validar Digitalización Lotes'), ('CREAR_ACTUALIZAR_AMBIENTACION', 'Crear/Actualizar Ambientación'), ('VALIDAR_ENRIQUECER_AMBIENTACION', 'Validar/Enriquecer Ambientación'), ('CORREGIR_GEOMETRIA_AMBIENTE', 'Corregir Geometría Ambiente'), ('PLANIFICAR_ORDEN_MUESTREO', 'Planificar Orden de Muestreo'), ('EJECUTAR_ORDEN_MUESTREO', 'Ejecutar Orden de Muestreo (Muestreador)'), ('PROCESAR_ANALISIS_SUELO', 'Procesar Análisis de Suelo')], max_length=100, verbose_name='Tipo de Tarea')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción Detallada')),
                ('estado_tarea', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ASIGNADA', 'Asignada (a usuario específico)'), ('EN_PROGRESO', 'En Progreso'), ('COMPLETADA', 'Completada'), ('BLOQUEADA', 'Bloqueada'), ('REQUIERE_CORRECCION', 'Requiere Corrección'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', max_length=30, verbose_name='Estado de la Tarea')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_limite', models.DateField(blank=True, null=True, verbose_name='Fecha Límite')),
                ('fecha_finalizacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Finalización')),
                ('object_id', models.PositiveIntegerField(verbose_name='ID de Entidad Relacionada')),
                ('comentarios_internos', models.TextField(blank=True, null=True, verbose_name='Comentarios Internos / Bitácora')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Tipo de Entidad Relacionada')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tareas_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Creado Por')),
            ],
            options={
                'verbose_name': 'Tarea de Workflow',
                'verbose_name_plural': 'Tareas de Workflow',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
