# Generated by Django 5.2 on 2025-05-07 17:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('usuarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='rol_asignado',
            field=models.ForeignKey(blank=True, help_text='Rol al que pertenece esta tarea.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.rol', verbose_name='Rol Grupal Asignado'),
        ),
        migrations.AddField(
            model_name='tarea',
            name='usuario_asignado_actualmente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tareas_tomadas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Asignado Actualmente'),
        ),
        migrations.AlterUniqueTogether(
            name='establecimiento',
            unique_together={('empresa', 'nombre')},
        ),
    ]
