# Generated by Django 5.2 on 2025-05-07 17:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id_rol', models.CharField(choices=[('cliente', 'Cliente/Productor'), ('area_gis', 'Área GIS'), ('area_ing_agronomo', 'Ingeniero Agrónomo'), ('area_logistica', 'Área Logística'), ('area_laboratorio', 'Área Laboratorio'), ('muestreador', 'Muestreador de Campo'), ('area_administracion', 'Área Administración'), ('area_gerencia', 'Área Gerencia'), ('admin_sistema', 'Administrador del Sistema')], max_length=50, primary_key=True, serialize=False, verbose_name='Identificador del Rol')),
                ('nombre_visible', models.CharField(max_length=100, verbose_name='Nombre Visible del Rol')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción del Rol')),
            ],
            options={
                'verbose_name': 'Rol de Usuario',
                'verbose_name_plural': 'Roles de Usuario',
                'ordering': ['nombre_visible'],
            },
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono_contacto', models.CharField(blank=True, max_length=50, null=True, verbose_name='Teléfono de Contacto Adicional')),
                ('activo', models.BooleanField(default=True, verbose_name='Perfil Activo')),
                ('empresa_asociada', models.ForeignKey(blank=True, help_text='Si el usuario es un cliente, a qué empresa representa.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.empresa', verbose_name='Empresa Asociada (para rol Cliente)')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_pronutrition', to=settings.AUTH_USER_MODEL, verbose_name='Usuario del Sistema')),
                ('rol', models.ForeignKey(blank=True, help_text='Rol principal del usuario en el sistema.', null=True, on_delete=django.db.models.deletion.PROTECT, to='usuarios.rol', verbose_name='Rol en ProNutrition')),
            ],
            options={
                'verbose_name': 'Perfil de Usuario ProNutrition',
                'verbose_name_plural': 'Perfiles de Usuario ProNutrition',
            },
        ),
    ]
